# Generated by Django 5.1 on 2024-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consecutive_days',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='ended_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
