# Generated by Django 5.0.1 on 2024-02-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jogo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
