# Generated by Django 5.0.1 on 2024-02-11 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChordNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('song_link', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Trainings',
            new_name='Training',
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Progress', 'verbose_name_plural': 'Progress'},
        ),
        migrations.AddField(
            model_name='progress',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
