# Generated by Django 5.0.1 on 2024-06-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0005_rename_name_level_profile_actual_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
